#ifndef IOCTRL_H
#define IOCTRL_H

#include <ntddk.h>

//网络信息监控
#define IOCTL_WFP_MONITOR \
	CTL_CODE(\
	FILE_DEVICE_UNKNOWN, \
	0x802, METHOD_BUFFERED, \
	FILE_READ_ACCESS | FILE_WRITE_ACCESS)

//网络规则增加
#define IOCTL_WFP_FORBIDDEN \
	CTL_CODE(\
	FILE_DEVICE_UNKNOWN, \
	0x803, METHOD_BUFFERED, \
	FILE_READ_ACCESS | FILE_WRITE_ACCESS)

//网络规则定向删除
#define IOCTL_WFP_REMOVE_RULE \
	CTL_CODE(\
	FILE_DEVICE_UNKNOWN, \
	0x804, METHOD_BUFFERED, \
	FILE_READ_ACCESS | FILE_WRITE_ACCESS)

//事件传递IOCTL
#define IOCTL_WFP_START_EVENT \
	CTL_CODE(\
	FILE_DEVICE_UNKNOWN, \
	0x822, METHOD_BUFFERED, \
	FILE_READ_ACCESS | FILE_WRITE_ACCESS)

//事件停止传递IOCTL
#define IOCTL_WFP_STOP_EVENT \
	CTL_CODE(\
	FILE_DEVICE_UNKNOWN, \
	0x823, METHOD_BUFFERED, \
	FILE_READ_ACCESS | FILE_WRITE_ACCESS)

//清除黑名单
#define IOCTL_WFP_CLEAR_BLACK_LIST\
	CTL_CODE(\
	FILE_DEVICE_UNKNOWN, \
	0x824, METHOD_BUFFERED, \
	FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#endif